name: Deploy Client Staging
on:
  push:
    branches:
      - staging
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 60
    env:
      VITE_CDN_URL: ${{ vars.VITE_CDN_URL }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Build dependencies packages
        run: pnpm turbo run build --filter @repo/shared --filter @repo/cdn

      - name: Build
        run: pnpm run build
        working-directory: packages/client

      - name: Deploy
        run: pnpm wrangler deploy --env stg
        working-directory: packages/client
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
